// <auto-generated />
using System;
using BlazorMasterDetails.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorMasterDetails.Migrations
{
    [DbContext(typeof(CustomerDb))]
    [Migration("20240313071300_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorMasterDetails.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            IsNew = true,
                            Name = "Sayem"
                        },
                        new
                        {
                            CustomerID = 2,
                            IsNew = true,
                            Name = "Jamir"
                        },
                        new
                        {
                            CustomerID = 3,
                            IsNew = true,
                            Name = "Enam"
                        });
                });

            modelBuilder.Entity("BlazorMasterDetails.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StandardCost")
                        .HasColumnType("int");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceID = 1,
                            CustomerId = 1,
                            InvoiceDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "AZ02u",
                            StandardCost = 1341
                        },
                        new
                        {
                            InvoiceID = 2,
                            CustomerId = 1,
                            InvoiceDate = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "LZ02u",
                            StandardCost = 1451
                        },
                        new
                        {
                            InvoiceID = 3,
                            CustomerId = 2,
                            InvoiceDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "EZ02u",
                            StandardCost = 521
                        },
                        new
                        {
                            InvoiceID = 4,
                            CustomerId = 2,
                            InvoiceDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "MZ02u",
                            StandardCost = 2652
                        },
                        new
                        {
                            InvoiceID = 5,
                            CustomerId = 3,
                            InvoiceDate = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "BZ02u",
                            StandardCost = 2526
                        });
                });

            modelBuilder.Entity("BlazorMasterDetails.Models.Invoice", b =>
                {
                    b.HasOne("BlazorMasterDetails.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BlazorMasterDetails.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
